### ISSUE TITLE
interference

### ISSUE THREAD

**Issue by UnknownNull** [platz1de/Waterlogging#3]
If we ban water on the server for normal players, they cannot put water on the block, but with this plugin, they can put water everywhere except the complete block.

**Comment by platz1de** [comment]
Can't reproduce this problem, this is probably a problem with whatever protection plugin you're using.
Can you send the name of that plugin or a code snipped responsible for blocking water interactions?
For reference this simple script works fine for me: https://gist.github.com/platz1de/7b47920447710f9d3e0622756d6f9615

**Comment by UnknownNull** [comment]
This plugin:
https://poggit.pmmp.io/p/BanItem-PM4/2.3.4

**Comment by platz1de** [comment]
Works for me using that plugin as well, clicking on waterloggable blocks causes client-side water appearing, which isn't caused by this plugin though and is exactly the same in vanilla pmmp.
I can try to add a workaround for this desync next version though (probably not happening until pmmp 5 release)

**Comment by UnknownNull** [comment]
> Can't reproduce this problem, this is probably a problem with whatever protection plugin you're using. Can you send the name of that plugin or a code snipped responsible for blocking water interactions? For reference this simple script works fine for me: https://gist.github.com/platz1de/7b47920447710f9d3e0622756d6f9615

However, it is still like this
